rte_pktmbuf_read 0x7a6d7d
rte_net_get_ptype 0x7a71d0
rte_constant_bswap16 0x7a6d3c
rte_lcore_id 0x802749 0x256b80 0x7a9e01 0x2c65e47
rte_pktmbuf_headroom 0x2c6b3df
rte_pktmbuf_reset 0x2c67211
rte_pktmbuf_reset_headroom 0x2c671d9
rte_mbuf_raw_alloc 0x2c66642
rte_ipv4_hdr_len 0x7a6dea
rte_pktmbuf_free 0x2c69374
rte_mbuf_refcnt_read 0x2c664da 0x7aa446
pmd_rx_burst 0x2c6cc62
pmd_tx_burst 0x2c6d6b1
pkt_burst_io_forward 0x23b96f
rte_eth_rx_burst 0x23ae4e 0x256bcb
common_fwd_stream_transmit 0x23b7ea
